version: '3.3'

# For development
services:

    # Database
    nodejstypescriptmysql:
        image: mysql:5.7
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: 'database'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes: 
            - ./mysql_data:/var/lib/mysql
        restart: "no"

    # Database Admin
    phpmyadm:
        depends_on:
            - nodejstypescriptmysql
        image: phpmyadmin/phpmyadmin
        restart: "no"
        ports:
            - '8082:80'
        environment:
            PMA_HOST: 'nodejstypescriptmysql'
            MYSQL_ROOT_PASSWORD: 'password'            